### ISSUE TITLE
Can we please have links to previous years sites?

### ISSUE THREAD

**Issue by mureinik** [kejbaly2/devconfcz#56]
The previous conferences had a whole lot of great content - video/audio recordings, slide decks, photo galleries, etc.
It would be great if the previous years sites would be made accessible somehow (e.g., as http://devconf.cz/2016 or http://2016.devconf.cz).

**Comment by kejbaly2** [comment]
Thanks for filing this. 

@frantisekz, we should chat about how we might do this. Since we moved to hosting on open shift, i'm not sure how easily it'll be to migrate the old (drupal?) platform there... Maybe we could work on at least migrating some of the old content to the new static site format though.

**Comment by frantisekz** [comment]
@kejbaly2 The old drupal site is up on OpenShift ( http://2016.devconf.cz/ ). The only issue is that we'have removed menu a and title page content before migration (rest of the content is still there). Will ping @vojtechtrefny as hi was webmaster on the drupal site.

**Comment by frantisekz** [comment]
@vojtechtrefny will look on this after the weekend.

**Comment by frantisekz** [comment]
So,
I am not very familiar with Drupal. I was able to put the menu back, without any styling.
It's there at least :)

http://2016.devconf.cz/

**Comment by frantisekz** [comment]
Regarding linking to the old website, I'll put it in the footer and create new PR for that.
